### PR TITLE
12.0 Backports

### PR DESCRIPTION
**Pull request by em230418**

### CODE REVIEW

**Review by blaquezzz — APPROVED** [review]

**Comment by GSLabIt** [comment]
@em230418 testing ur pr, getting and error setting admin to build:

```
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/dev/odoo-dev/odoo-dev12/odoo/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_limit_max_users/models/saas_db.py", line 26, in write
    return super(SaasDb, self).write(vals)
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_build_admin/models/saas_db.py", line 21, in write
    return super(SaasDb, self).write(vals)
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas/models/saas_db.py", line 65, in write
    self.refresh_data()
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas/models/saas_db.py", line 76, in refresh_data
    record.write_values_to_build()
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_apps_signup/models/saas_db.py", line 49, in write_values_to_build
    super(SaasDb, self).write_values_to_build()
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_limit_max_users/models/saas_db.py", line 43, in write_values_to_build
    super(SaasDb, self).write_values_to_build()
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_expiration/models/saas_db.py", line 18, in write_values_to_build
    super(SaasDb, self).write_values_to_build()
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_database_limit/models/saas_db.py", line 14, in write_values_to_build
    super(SaasDb, self).write_values_to_build()
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_build_admin/models/saas_db.py", line 66, in write_values_to_build
    self.execute_kw(model, "write", res_id, vals)
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas/models/saas_db.py", line 85, in execute_kw
    return self.operator_id.build_execute_kw(self, model, method, args, kwargs)
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas/models/saas_operator.py", line 169, in build_execute_kw
    return self._build_execute_kw(build.name, model, method, args, kwargs)
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas_operator_remote/models/saas_operator.py", line 99, in _build_execute_kw
    db_name, model, method, args, kwargs
  File "/dev/odoo-dev/odoo-dev12/custom/saas-addons/saas/models/saas_operator.py", line 163, in _build_execute_kw
    return execute(db_name, SUPERUSER_ID, model, method, *args, **kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/service/model.py", line 185, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/service/model.py", line 169, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/dev/odoo-dev/odoo-dev12/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/dev/odoo-dev/odoo-dev12/custom/access-addons/access_limit_max_users/models/res_users.py", line 22, in write
    if vals.get("is_excluded_from_limiting") and not self.env.user._is_superuser():
AttributeError: 'int' object has no attribute 'get'
```

Any hint?

**Comment by em230418** [comment]
Hi, @GSLabIt!
The problem is already resolved https://github.com/itpp-labs/access-addons/pull/298
As for now, you can clone my fork of access-addons and use it. https://github.com/em230418/access-addons/tree/12.0

Bump @trojikman

**Comment by GSLabIt** [comment]
@em230418 thanks, I'll have a look. I'm experiencing some other issues. Will open in a few.

**Comment by GSLabIt** [comment]
a couple of other issues:

* if queue channel has more than 1 channel `post_init` will file because database is not yet created.
* issue when updating contract line on register payment for first invoice, basically it doesn't find line because is not yet paid.

Could you double check?  Thx

**Comment by Ramil-Mukhametzyanov** [comment]
> a couple of other issues:
> 
>     * if queue channel has more than 1 channel `post_init` will file because database is not yet created.
> 
>     * issue when updating contract line on register payment for first invoice, basically it doesn't find line because is not yet paid.
> 
> 
> Could you double check? Thx

Hello,
@GSLabIt 
You did great work! If you need our assistance in checking and fixing issues, knock to our email: it@it-projects.info.
Wish you good.

**Pull request merged**
